import { AboutSection, ContactSection, HeroSection, Layout, Services } from "@/src/components";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Boomba-Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/coffee.ico" />
      </Head>

      <main className="overflow-x-hidden">
        <HeroSection />
        <AboutSection />
        <Services />
        <ContactSection />
      </main>
    </>
  );
}

Home.Layout = Layout;
